package main.java.leetcode;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

public class FindDiffChar {
    public char findTheDifference(String s, String t) {
        int currentIndex;
        int[] currentCount = new int[26];
        int index;
        for(index = 0; index < s.length(); index++) {
            currentIndex = s.charAt(index) - 'a';
            currentCount[currentIndex]++;
        }
        for(index = 0; index < t.length(); index++) {
            char compareChar = t.charAt(index);
            currentIndex = compareChar - 'a';
            if(currentCount[currentIndex] == 0) {
                return compareChar;
            }
            currentCount[currentIndex]--;
        }
        return '\0';
    }
}
